package br.com.triagem_ia_sus.triagem_ia_sus.domain;

public enum StatusAtendimento {
    AGUARDANDO_TRIAGEM_ESPECIALIZADA,
    TRIAGEM_ESPECIALIZADA_EM_ANDAMENTO,
    AGUARDANDO_ATENDIMENTO_ESPECIALIZADO,
    ATENDIMENTO_ESPECIALIZADO_EM_ANDAMENTO,
    ATENDIMENTO_EM_ANDAMENTO_VIA_CANAL,
    FINALIZADO

}
